### ISSUE TITLE
Some unexpected issues in the  step4

### ISSUE THREAD

**Issue by junchenhe123** [pernak18/ABSCO#23]
(absco) hjc@hjc-virtual-machine: ./RTABSCO/ABSCO$ ./build_models.py -c gfortran -i ABSCO_config.ini
Traceback (most recent call last):
  File "./RTABSCO/ABSCO/./build_models.py", line 272, in <module>
    subObj.getLineFile()
  File "./RTABSCO/ABSCO/./build_models.py", line 116, in getLineFile
    zget([str(self.zRecID), '-w', arcList])
TypeError: 'module' object is not callable

**Comment by pernak18** [comment]
@junchenhe123 what is your version of `zenodo_get`?
